### ISSUE TITLE
Missing SDist for 2.7.1

### ISSUE THREAD

**Issue by henryiii** [DanielBok/nlopt-python#14]
The SDist is missing on PyPI for 2.7.1, which has made it impossible to update in Pyodide for the 0.20 (Python 3.10!) release. 2.6.2 seems to be the last one with an SDist. `pipx run build --sdist` should produce one for upload.

**Comment by DanielBok** [comment]
Hello, not gonna support an sdist as building the wheels are hard enough :(

But willing to merge any PR that adds support to this
