### ISSUE TITLE
Please add release on PyPI for python 3.11

### ISSUE THREAD

**Issue by AntoineD** [DanielBok/nlopt-python#19]

**Comment by AntoineD** [comment]
@DanielBok @HDembinski  Would it be possible for you to build the package for python 3.11?

**Comment by AntoineD** [comment]
@HDembinski @DanielBok Please let me know if you intend to build a python 3.11 package.

**Comment by HDembinski** [comment]
Hi, I haven't been very active since I joined, but I can give it a try if Daniel is busy.

**Comment by AntoineD** [comment]
That would be awesome! Thanks.

**Comment by HDembinski** [comment]
@AntoineD Looks like Daniel has already started working on supporting 3.11, see https://github.com/DanielBok/nlopt-python/tree/develop/3.11

**Comment by DanielBok** [comment]
@HDembinski couldn't figure out why the cmake wouldn't build in the github actions. If you have some time, could you take a look at it? (I'm not proficient with cmake)

**Comment by HDembinski** [comment]
I had a look at the CI logs, but I do not see why it is failing. It is funny that Windows 3.11 succeeds, while every other platform fails.

I can try to build the wheel locally to better understand the issue.

**Comment by AntoineD** [comment]
In the short term and in order to be able to use the package with 3.11, how about just building for python 3.11 and push the packages to PyPI?

**Comment by HDembinski** [comment]
@AntoineD I also thought that it is that simple, but apparently not. nlopt-python is not released very often and it seems that in the meantime some GitHub update broke our builds. At least that's how I understand the situation from looking at the logs, but @DanielBok should know better.

**Comment by AntoineD** [comment]
From the git history it looks like you @DanielBok is trying to build an updated version of nlopt.
Would it be possible to build the already last released version of nlopt-python just for python 3.11? That seems possible by disabling the build for all other python versions of the github actions.

**Comment by AntoineD** [comment]
Hello, how about the suggestion in my previous post?

**Comment by FrancoisGallard** [comment]
Hello,
Having nlopt work with python 3.11 would be really great since it provides a huge performance boost.
Is there anything we can do to help?

Thanks
François

**Comment by LukeLabrie** [comment]
Would also be interested in having a python3.11-compatibile version

**Comment by peterdsharpe** [comment]
Hi all,

Seconding (or, fifth-ing?) that this `nlopt`-on-3.11 issues causing a block for us as well in building downstream packages:

https://github.com/CadQuery/cadquery/issues/1248

With Python 3.11 becoming increasingly common in the wild these days, I suspect that this will begin to affect a ever-growing fraction of `nlopt-python`'s user base.

@DanielBok @HDembinski , any word on when a 3.11 build on PyPI will be available?

**Comment by mojca** [comment]
Is NumPy optional?
```
Could NOT find NumPy (missing: NUMPY_INCLUDE_DIRS)
```

And the second weird thing. There seems to be some mixup between Python 3.11 and 3.8. The same build job finds both, and when I install the package on Windows with Python 3.11, it just installs the one with 3.8 in the name.

**Comment by DanielBok** [comment]
Hi all, added 3.11. 

Thank you @khwilson who helped with the mac build.

**Comment by khwilson** [comment]
Glad to help! Congrats on the release and thanks again for all the work!

**Comment by FrancoisGallard** [comment]
Great, thank you very much !
