### ISSUE TITLE
Package for python 2.7

### ISSUE THREAD

**Issue by AntoineD** [DanielBok/nlopt-python#2]
Hello Daniel,

nlopt v2.6.1 has a [anaconda package for python 2.7](https://anaconda.org/conda-forge/nlopt/files) (which works OK for our applications) but there is no such package in PyPI.
This makes our deployment process a bit tricky because for our applications we target python 2.7 and 3.6+ under both pip and anaconda environments.

Would it be possible for you to create a PyPI package of nlopt v.2.6.1 for pyhon 2.7?

**Comment by AntoineD** [comment]
Hi Daniel,

are you still maintaining this package?

**Comment by DanielBok** [comment]
Hello @AntoineD, yup I'm still maintaining it. Sorry didn't get your message as the issue wasn't routed to my mailbox. Presently, we won't be supporting python 2.7 anymore, since it has already reached EOL. I'd recommend moving to 3.8+ 👍
