### ISSUE TITLE
release for python 3.12

### ISSUE THREAD

**Issue by loixou** [DanielBok/nlopt-python#24]
Hi,

Is there any release for python 3.12?
It would be awesome to get that one.

Please take me in touch if you're planning to create one.

Thanks,

**Comment by jonas-eschle** [comment]
@DanielBok , any plans for the release? Or anything we can do to help?

**Comment by DanielBok** [comment]
@jschueller I couldn't get the build to work, see this [branch](https://github.com/DanielBok/nlopt-python/pull/28).

The build logs are [here](https://github.com/DanielBok/nlopt-python/actions/runs/8290038085)

Could you advise why the build is failing?

**Comment by jschueller** [comment]
nlopt needs patching, see #29

**Comment by DanielBok** [comment]
Done. Thank you @jschueller for the help
