### ISSUE TITLE
numpy 2.x rebuild

### ISSUE THREAD

**Issue by jschueller** [DanielBok/nlopt-python#35]
it needs a rebuild for numpy 2.x compatibility

**Comment by ferrigno** [comment]
Is there a foreseen date for the release of this rebuild? Thanks

**Comment by darrellenns** [comment]
For anyone else dealing with this, I was able to build it locally (in a python:3.12 docker container) as follows:

# install cmake
apt update
apt install cmake

#clone and build nlopt
git clone https://github.com/DanielBok/nlopt-python.git
cd nlopt-python/
git submodule update --init --recursive
python -m pip install -U pip numpy swig wheel setuptools
python setup.py bdist_wheel -d dist

The resulting .whl file is in /nlopt-python/dist, and can be installed in whatever other venv's you need it in. It seems to work fine with numpy 2.0+.

It would be really nice if a new build could by pushed to pypi, so users don't have to jump through these hoops.

**Comment by DanielBok** [comment]
Done. See this [PR](https://github.com/DanielBok/nlopt-python/pull/38)
