### ISSUE TITLE
Request: Update pypi tags to be compatible with Python 3.10

### ISSUE THREAD

**Issue by wbthomason** [DanielBok/nlopt-python#8]
It seems that the latest PyPI release of this package is only tagged as compatible with Python versions through 3.9.9. Assuming it's the case, could you please update the tags to indicate compatibility with Python 3.10, and allow tools like `poetry` to correctly install `nlopt` for Python 3.10?

**Comment by henryiii** [comment]
It's just missing 3.10 wheels. This is one of the last two remaining packages in pyodide that doesn't have Python 3.10 wheels. Would it be possible to add them? See https://github.com/pyodide/pyodide/issues/978.

**Comment by hoodmane** [comment]
Not that Pyodide can use manylinux wheels, we're just using the presence of a wheel as a signal of Python 3.10 compatibility.

**Comment by DanielBok** [comment]
Sorry for the delay, was a little caught up by work. I've since added the workflow for the 3.10 wheels. The wheels should be built and uploaded to pypi now.
